import "./globals.css";

import Header from "@/components/templates/header";
import Footer from "@/components/templates/footer/Footer";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import PageTransition from "@/components/atom/PageTransition";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className="min-h-screen">
        <TanstackQueryProvider>
          <div className="flex min-h-screen flex-col">
            {/* Header */}
            <Header />

            <NextTopLoader
              color="#DC2626"
              showSpinner={false}
            />

            {/* Main Content */}
            <main className="flex-1 min-h-0 pb-20 lg:pb-0">
              <PageTransition>
                {children}
              </PageTransition>
            </main>

            {/* Footer */}
            <Footer />
          </div>

          <Toaster />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}