
import "./globals.css";
import Header from "@/components/templates/header";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className={``}>
        <TanstackQueryProvider>

        <Header/>
        <main>
        {children}

        </main>
        </TanstackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
